// require("./scss/index___scss/")
// require("./scss/rozklad.scss")
require("./scss/common___scss/index.scss")
require("./scss/rozklad___scss/rozklad.scss")
require("./scss/common___scss/navigation/nav___scss.scss")
require("./scss/common___scss/overall_titling/title.scss")
require("./scss/photo___scss/photo_scss.scss")
require("./scss/news___scss/news_scss.scss")
require("./scss/index___scss/index___scss.scss")
require("./scss/common___scss/footer/footer_scss.scss")