// require("./less/index___less/")
// require("./less/rozklad.less")
require("./less/common___less/index.less")
require("./less/rozklad___less/rozklad.less")
require("./less/common___less/navigation/nav___less.less")
require("./less/common___less/overall_titling/title.less")
require("./less/photo___less/photo_less.less")
require("./less/news___less/news_less.less")
require("./less/index___less/index___less.less")
require("./less/common___less/footer/footer_less.less")